/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/patrickm/zephyrproject/zephyr/samples/dds_hello_world/src/HelloWorldData.h
  Source: /home/patrickm/zephyrproject/zephyr/samples/dds_hello_world/cyclonedds/examples/helloworld/HelloWorldData.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__HOME_PATRICKM_ZEPHYRPROJECT_ZEPHYR_SAMPLES_DDS_HELLO_WORLD_SRC_HELLOWORLDDATA_H
#define DDSC__HOME_PATRICKM_ZEPHYRPROJECT_ZEPHYR_SAMPLES_DDS_HELLO_WORLD_SRC_HELLOWORLDDATA_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct HelloWorldData_Msg
{
  int32_t userID;
  char * message;
} HelloWorldData_Msg;

extern const dds_topic_descriptor_t HelloWorldData_Msg_desc;

#define HelloWorldData_Msg__alloc() \
((HelloWorldData_Msg*) dds_alloc (sizeof (HelloWorldData_Msg)));

#define HelloWorldData_Msg_free(d,o) \
dds_sample_free ((d), &HelloWorldData_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_PATRICKM_ZEPHYRPROJECT_ZEPHYR_SAMPLES_DDS_HELLO_WORLD_SRC_HELLOWORLDDATA_H */
